### PR TITLE
Implemented the split string function

### PR DESCRIPTION
**Pull request by mauricerivers**
Implemented the split string function.
Also added at the bottom a quick example of how it may be used.

😄

### CODE REVIEW

**Comment by mauricerivers** [comment]
Will have an updated version later today.
Thanks

**Comment by mauricerivers** [comment]
I have made some updates to my code. Any feedback/suggestion is welcomed.

**Comment by giordanna** [comment]
Hi there, I would like to question why you would expect the output `["adhu", "wjakdlsj", "asdlkwja"]` if you use `"adhu wjakdlsj asdlkwja".mysplit('a',2)`, since by using the original split function the output is `[ "", "dhu wj" ]`

**Comment by TheSTL** [comment]
Thanks @giordanna for pointing . I have corrected the mistakes.

**Comment by TheSTL** [comment]
I'm closing this PR.
Merged PR is - [#35]

**Pull request closed without merging**
